### ISSUE TITLE
Integrate a few development tools and frameworks

### ISSUE THREAD

**Issue by eignatik** [eignatik/LOAD.x#42]
There are a few frameworks that should be integrated into this project: 
- Springboot (to provide kinda beans container)
- Jackson (to operate with JSON, it can be helpful for statistic results and so on)
- Maybe it's gonna be Hibernate ORM instead of SQL2O (I think it should be)

**Comment by lightway82** [comment]
Для этого проекта нужно брать что-то реально асинхронное, а не многопоточное, тк каждый поток в JVM уж больно много жрет

**Comment by lightway82** [comment]
Также в идеале делать как микросервис, с возможностью горизонтального масштабирования на несколько серверов, для увеличения нагрузки

**Comment by eignatik** [comment]
@lightway82, я хочу сначала реализовать многопоточное приложение, а потом уже думать об асинхронной реализации, как о расширении. Что качается микроскопичной архитектуры - посмотрим, пока что мои задачи немного в другом лежат

**Comment by eignatik** [comment]
Spring has been interated into project. The card for configuration, etc will be created soon.
